version = 0.1

[default.deploy.parameters]
stack_name = "fastapi-backend"
resolve_s3 = true
s3_prefix = "fastapi-backend"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=\"dev\""
confirm_changeset = true

[default.global.parameters]
region = "us-east-1"
